apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
  namespace: shopping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - name: sprintboot-application
        image: nareshprk/test:v3
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-svc
  namespace: shopping
spec:
  selector:
    app: springboot
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
  type: NodePort