apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: shopping
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "codilar"
            - name: MYSQL_DATABASE
              value: "shoppingcart"
            - name: MYSQL_USER
              value: "naresh"
            - name: MYSQL_PASSWORD
              value: "Naresh@123"
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "mysqladmin ping -h 127.0.0.1 -uroot -pcodilar"
            initialDelaySeconds: 5
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: mysql-persistent-storage
        namespace: shopping
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: shopping
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
      name: mysql
  type: ClusterIP
  selector:
    app: mysql